### ISSUE TITLE
[Question] haskell-c-mode ?

### ISSUE THREAD

**Issue by ocramz** [flycheck/flycheck.github.io#1]
What should I modify to have Haskell linting/typechecking when editing c2hs .chs files (Haskell with C #includes and c2hs {# ... #} macros) ?

I already have FlyCheck working in haskell-mode and C mode sepately.

Thank you in advance

**Comment by purcell** [comment]
Which major mode are you using for `.chs`? That's usually how `flycheck` chooses a checker.

**Comment by ocramz** [comment]
It's showing (Haskell-C Ind Doc) and I switch it on with M-x haskell-c-mode, is this what you mean? I'm not exactly an Emacs expert..

**Comment by lunaryorn** [comment]
@purcell @ocramz You're definitely discussing this in the wrong repo.  Please move over to the right tracker.

**Comment by ocramz** [comment]
sorry about this
