### ISSUE TITLE
Use light or extra light source serif variant for italics

### ISSUE THREAD

**Issue by lunaryorn** [flycheck/flycheck.github.io#15]
In the absence of italics in Source Serif Pro, we could try to use the light or extra light variant for italics.

Currently we'll just get a random italic serif font because we make no provisions for a custom font with italics.

**Comment by cpitclaudel** [comment]
Ubuntu Mono works pretty nicely too for screenshots. I use it for the screenshots at https://github.com/cpitclaudel/company-coq/#screenshots (warning: there are gifs ^^), if you want to have a look

**Comment by lunaryorn** [comment]
@cpitclaudel I think there's a misunderstanding here.  I was referring to the serif font used in the body text of the website 🙂

**Comment by cpitclaudel** [comment]
Ooooh, ok :) I read Source Code Pro for whatever reason ^^
