### ISSUE TITLE
Lato font broken in Windows

### ISSUE THREAD

**Issue by andrelaszlo** [flycheck/flycheck.github.io#2]
My colleague is browsing flycheck.org in Chrome, Firefox and IE (10, I think).

The page loads and all text show up initially, but when the font loads some characters disappear, making the page hard to read. All "f":s and "p":s are replaced by blank spaces, it seems :smile: 

Not sure if it's related to [this](https://code.google.com/p/googlefontdirectory/issues/detail?id=331), but maybe a newer version of Lato would fix this issue.

**Comment by lunaryorn** [comment]
@andrelaszlo I'm using the latest Lato version from http://www.latofonts.com/lato-free-fonts/.  There's nothing to fix on this side. I'm inclined to blame Windows font rendering, and call it a day.   Flycheck does not officially support Windows anyway, and personally I don't care for Windows at all.

If you could tell me the Windows version your colleague is using, I'd run a quick Google and search for some obvious fix, but if there isn't any, I'm not going to spend a lot of time on this one.

Pull requests or patches are welcome.

**Comment by andrelaszlo** [comment]
OK, then it should work I guess. Don't waste your time on it! Maybe a reboot will fix it :wink:

I'll see if I can reproduce this when I get home.

**Comment by lunaryorn** [comment]
@andrelaszlo Could you reproduce this issue?  Is Lato broken on other Windows systems, too?

**Comment by lunaryorn** [comment]
I failed to reproduce this issue on two different Windows systems, so I'm going to close this.  I'm sorry that it doesn't work for you, but I don't want to spend my time on hunting magic bugs.
